### ISSUE TITLE
Make: ***[all] Error 2

### ISSUE THREAD

**Issue by csk1nner** [Open-Transactions/opentxs#603] opened 2015-06-26 11:03 UTC
Hello Gang,

I just spun up an Ubuntu 14 server with a gcc of 4.9.2 (gcc --version)  I've got the cmake .. to build/find everything without a problem.  When I run the make -j(x) or sudo make -j5 command it fails with the following:

cc1plus: all warnings being treated as errors
make[2] *** [src/core/CMakeFiles/opentxs-core.dir/OTServerContract.cpp.o] Error 1
make[2] Leaving directory '/applications/opentxs/build'
make[1] *** [src/cort/CMakeFiles/opentxs-core.dir/all] Error 2
make[1]: Leaving directory '/applications/opentxs/build'
make: *** [all] Error 2

Any ideas?

Thanks,

Caleb

**Comment by lclc** [comment] 2015-06-26 15:35
Please post the full output starting from cmake .. to the end of make.

Also, you can do j2, j4, j6, j8 etc. but no odd numbers afaik (you can, but it wont have an effect).

**Comment by csk1nner** [comment] 2015-06-26 16:19
No problem!

Here's the cmake ..
-----------------------
caleb@ubuntu14:/applications/opentxs/build$ sudo cmake ..
[sudo] password for caleb:
no talloc stackframe at ../source3/param/loadparm.c:4864, leaking memory
-- General -------------------------------------
-- opentxs version:        0.94.0-579-gcd94b49
-- CMake version:          2.8.12.2
-- System:                 Linux-3.16.0-30-generic
-- Processor:              x86_64
-- Verbose:                ON
-- Testing:                ON
-- Documentation:          ON
-- Using ccache            OFF
-- Packaging -----------------------------------
-- Build RPM:              OFF
-- Build DEB:              OFF
-- Package Contact:
-- Package Vendor:         Open Transactions Developers
-- CL autocompletion:      OFF
-- Keyrings ------------------------------------
-- Keyring Windows:        OFF
-- Keyring MAC:            OFF
-- Keyring iOS:            OFF
-- Keyring Gnome:          OFF
-- Keyring KWallet:        OFF
-- Keyring flatfile:       OFF
-- Bindings ------------------------------------
-- Java binding:           OFF
-- Perl binding:           OFF
-- PHP binding:            OFF
-- Python binding:         OFF
-- C++ Compiler ID: GNU
-- C++ Flags:        -std=c++11 -pthread -fPIC
-- C++ link flags:
-- version: 3.0.1
-- install: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /applications/opentxs/build
caleb@ubuntu14:/applications/opentxs/build$
------------------
Here's the build
-------------------
caleb@ubuntu14:/applications/opentxs/build$ sudo make
/usr/bin/cmake -H/applications/opentxs -B/applications/opentxs/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /applications/opentxs/build/CMakeFiles /applications/opentxs/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/applications/opentxs/build'
make -f deps/CMakeFiles/anyoption.dir/build.make deps/CMakeFiles/anyoption.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps /applications/opentxs/build /applications/opentxs/build/deps /applications/opentxs/build/deps/CMakeFiles/anyoption.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/CMakeFiles/anyoption.dir/build.make deps/CMakeFiles/anyoption.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/CMakeFiles/anyoption.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[  0%] Built target anyoption
make -f deps/CMakeFiles/bitcoin-base58.dir/build.make deps/CMakeFiles/bitcoin-base58.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps /applications/opentxs/build /applications/opentxs/build/deps /applications/opentxs/build/deps/CMakeFiles/bitcoin-base58.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/CMakeFiles/bitcoin-base58.dir/build.make deps/CMakeFiles/bitcoin-base58.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/CMakeFiles/bitcoin-base58.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[  0%] Built target bitcoin-base58
make -f deps/CMakeFiles/lucre.dir/build.make deps/CMakeFiles/lucre.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps /applications/opentxs/build /applications/opentxs/build/deps /applications/opentxs/build/deps/CMakeFiles/lucre.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/CMakeFiles/lucre.dir/build.make deps/CMakeFiles/lucre.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/CMakeFiles/lucre.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[  0%] Built target lucre
make -f deps/gtest/CMakeFiles/gtest.dir/build.make deps/gtest/CMakeFiles/gtest.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps/gtest /applications/opentxs/build /applications/opentxs/build/deps/gtest /applications/opentxs/build/deps/gtest/CMakeFiles/gtest.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/gtest/CMakeFiles/gtest.dir/build.make deps/gtest/CMakeFiles/gtest.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/gtest/CMakeFiles/gtest.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[  0%] Built target gtest
make -f deps/gtest/CMakeFiles/gtest_main.dir/build.make deps/gtest/CMakeFiles/gtest_main.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps/gtest /applications/opentxs/build /applications/opentxs/build/deps/gtest /applications/opentxs/build/deps/gtest/CMakeFiles/gtest_main.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/gtest/CMakeFiles/gtest_main.dir/build.make deps/gtest/CMakeFiles/gtest_main.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/gtest/CMakeFiles/gtest_main.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[  0%] Built target gtest_main
make -f deps/irrxml/CMakeFiles/irrxml.dir/build.make deps/irrxml/CMakeFiles/irrxml.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps/irrxml /applications/opentxs/build /applications/opentxs/build/deps/irrxml /applications/opentxs/build/deps/irrxml/CMakeFiles/irrxml.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/irrxml/CMakeFiles/irrxml.dir/build.make deps/irrxml/CMakeFiles/irrxml.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/irrxml/CMakeFiles/irrxml.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles  17
[  1%] Built target irrxml
make -f deps/czmq/CMakeFiles/czmq.dir/build.make deps/czmq/CMakeFiles/czmq.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/deps/czmq /applications/opentxs/build /applications/opentxs/build/deps/czmq /applications/opentxs/build/deps/czmq/CMakeFiles/czmq.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f deps/czmq/CMakeFiles/czmq.dir/build.make deps/czmq/CMakeFiles/czmq.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `deps/czmq/CMakeFiles/czmq.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
[ 16%] Built target czmq
make -f src/core/recurring/CMakeFiles/opentxs-recurring.dir/build.make src/core/recurring/CMakeFiles/opentxs-recurring.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/src/core/recurring /applications/opentxs/build /applications/opentxs/build/src/core/recurring /applications/opentxs/build/src/core/recurring/CMakeFiles/opentxs-recurring.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f src/core/recurring/CMakeFiles/opentxs-recurring.dir/build.make src/core/recurring/CMakeFiles/opentxs-recurring.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `src/core/recurring/CMakeFiles/opentxs-recurring.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles  87
[ 17%] Built target opentxs-recurring
make -f src/core/otprotob/CMakeFiles/otprotob.dir/build.make src/core/otprotob/CMakeFiles/otprotob.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/src/core/otprotob /applications/opentxs/build /applications/opentxs/build/src/core/otprotob /applications/opentxs/build/src/core/otprotob/CMakeFiles/otprotob.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f src/core/otprotob/CMakeFiles/otprotob.dir/build.make src/core/otprotob/CMakeFiles/otprotob.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `src/core/otprotob/CMakeFiles/otprotob.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles  97 98 99
[ 20%] Built target otprotob
make -f src/core/trade/CMakeFiles/opentxs-trade.dir/build.make src/core/trade/CMakeFiles/opentxs-trade.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/src/core/trade /applications/opentxs/build /applications/opentxs/build/src/core/trade /applications/opentxs/build/src/core/trade/CMakeFiles/opentxs-trade.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f src/core/trade/CMakeFiles/opentxs-trade.dir/build.make src/core/trade/CMakeFiles/opentxs-trade.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `src/core/trade/CMakeFiles/opentxs-trade.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles  96
[ 21%] Built target opentxs-trade
make -f src/core/cron/CMakeFiles/opentxs-cron.dir/build.make src/core/cron/CMakeFiles/opentxs-cron.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/src/core/cron /applications/opentxs/build /applications/opentxs/build/src/core/cron /applications/opentxs/build/src/core/cron/CMakeFiles/opentxs-cron.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f src/core/cron/CMakeFiles/opentxs-cron.dir/build.make src/core/cron/CMakeFiles/opentxs-cron.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `src/core/cron/CMakeFiles/opentxs-cron.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[ 21%] Built target opentxs-cron
make -f src/core/script/CMakeFiles/opentxs-script.dir/build.make src/core/script/CMakeFiles/opentxs-script.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/src/core/script /applications/opentxs/build /applications/opentxs/build/src/core/script /applications/opentxs/build/src/core/script/CMakeFiles/opentxs-script.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f src/core/script/CMakeFiles/opentxs-script.dir/build.make src/core/script/CMakeFiles/opentxs-script.dir/build
make[2]: Entering directory `/applications/opentxs/build'
make[2]: Nothing to be done for `src/core/script/CMakeFiles/opentxs-script.dir/build'.
make[2]: Leaving directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles  88 89 90 91
[ 25%] Built target opentxs-script
make -f src/core/CMakeFiles/opentxs-core.dir/build.make src/core/CMakeFiles/opentxs-core.dir/depend
make[2]: Entering directory `/applications/opentxs/build'
cd /applications/opentxs/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /applications/opentxs /applications/opentxs/src/core /applications/opentxs/build /applications/opentxs/build/src/core /applications/opentxs/build/src/core/CMakeFiles/opentxs-core.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/applications/opentxs/build'
make -f src/core/CMakeFiles/opentxs-core.dir/build.make src/core/CMakeFiles/opentxs-core.dir/build
make[2]: Entering directory `/applications/opentxs/build'
/usr/bin/cmake -E cmake_progress_report /applications/opentxs/build/CMakeFiles
[ 25%] Building CXX object src/core/CMakeFiles/opentxs-core.dir/OTServerContract.cpp.o
cd /applications/opentxs/build/src/core && /usr/bin/c++   -DCHAISCRIPT_NO_THREADS -DEXPORT="" -DOT_CASH_USING_LUCRE -DOT_CRYPTO_USING_OPENSSL -DOT_PREFIX_PATH=\"/usr/local\" -Dopentxs_core_EXPORTS -std=c++11 -pthread -fPIC -Wall -Werror -Wextra -pedantic -Wno-missing-braces -Wcast-align -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wmissing-include-dirs -Wswitch-default -Wold-style-cast -Wredundant-decls -Woverloaded-virtual -Wmissing-declarations -Wunused-macros -Wundef -Wformat=2 -Wno-format-nonliteral -Wnoexcept -Wstrict-null-sentinel -Wlogical-op -Wuseless-cast -O3 -DNDEBUG -fPIC -isystem /applications/opentxs/src/../deps -isystem /applications/opentxs/src/../deps/ChaiScript/include -isystem /applications/opentxs/src/../deps/lucre/include -I/applications/opentxs/build/src/../include -I/applications/opentxs/src/../include -isystem /applications/opentxs/deps/czmq/include -I/applications/opentxs/build/src/core/otprotob    -o CMakeFiles/opentxs-core.dir/OTServerContract.cpp.o -c /applications/opentxs/src/core/OTServerContract.cpp
/applications/opentxs/src/core/OTServerContract.cpp: In destructor ‘virtual opentxs::OTServerContract::~OTServerContract()’:
/applications/opentxs/src/core/OTServerContract.cpp:81:63: error: useless cast to type ‘uint8_t* {aka unsigned char*}’ [-Werror=useless-cast]
         uint8_t * pKey = static_cast<uint8_t *>(m_transportKey);
                                                               ^
cc1plus: all warnings being treated as errors
make[2]: *** [src/core/CMakeFiles/opentxs-core.dir/OTServerContract.cpp.o] Error 1
make[2]: Leaving directory `/applications/opentxs/build'
make[1]: *** [src/core/CMakeFiles/opentxs-core.dir/all] Error 2
make[1]: Leaving directory `/applications/opentxs/build'
make: *** [all] Error 2
caleb@ubuntu14:/applications/opentxs/build$

**Comment by yamamushi** [comment] 2015-06-26 17:10
Thanks for that. With this we can see that the error is being thrown because GCC is treating the warning as an error, now we just need to determine how best to deal with it portably.

**Comment by csk1nner** [comment] 2015-06-26 17:16
I thought this looked like a compiler setting.  But I'm not a gcc expert.

C

**Comment by yamamushi** [comment] 2015-06-29 17:01
I am closing this ticket as a duplicate of #599 , please reference that ticket for further communications on this issue.

**Closed by yamamushi** 2015-06-29 17:01 UTC
