### ISSUE TITLE
MEP-2: Support CurveZMQ key format in credential system

### ISSUE THREAD

**Issue by OttoAllmendinger** [Open-Transactions/opentxs#434] opened 2014-11-19 10:51 UTC
See #392 

First target use case: ["Stonehouse Pattern"](http://hintjens.com/blog:49#toc5)

* The client needs to be able to get the server's public key ("auth key" in subcredential) from the `notaryProviderContract` in order to establish the connection.
* The notary needs to be able to load the corresponding private key from the local storage.

**Comment by haarts** [comment] 2015-02-20 16:06
Duplicate of #553

**Closed by haarts** 2015-02-20 16:06 UTC
